### ISSUE TITLE
Feedback form Backend Email

### ISSUE THREAD

**Issue by kode-logger** [Open-Source-Community-VIT-AP/oschub#60]
**Describe the bug**
This bug can be fixed by replacing the email id with osc mail id. The bug lets the code to send the feedback message to a developer's test email rather than sending it to the club mail id.

**To Reproduce**
Steps to reproduce the behaviour:
1. Open https://osc-hub.herokuapp.com/dashboard/about/
2. Scroll down to the end of the page
3. Fill in the feedback 
4. The feedback will be sent successfully to the test email instead of the club's official email.

**Expected behavior**
The feedback form in about.html will not be sending any feedbacks to the osc instead all the feedback will be sent to the already existing developer's test email.

**Screenshots**

Screenshot of the line that needs to be fixed.
![image](https://user-images.githubusercontent.com/55313761/126133907-8d22df53-4f69-4a77-8b45-6ef63bb81723.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Edge
 - Version: 91.0.864.70

**Smartphone (please complete the following information):**

**Comment by kode-logger** [comment]
Commit b306dfd  Fixed the issue.

**Comment by dat-adi** [comment]
![image](https://user-images.githubusercontent.com/31721284/126370215-c4a7d475-06a0-4a16-ab94-821a3e6e3fe9.png)
Unsure as to whether the issue is resolved, could you add an explanation as to why the SMTP Authentication fails?

I'm supposing that it has to do with the Google API not providing the users with access to send mails via SMTP, might wish to check this issue out?
In order to avoid necrobumping, I recommend a new issue created for it.
